
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./custom2.css";
import React from "react";
import  "bootstrap/dist/css/bootstrap.min.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
  children: React.ReactNode;
}>

) {
  return (
    <html lang="en">
      {
      //  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
      //   <div className="container">
      //     <div className="row">
      //       <div className="col-12">
      //         <h1 className="text-center">Welcome to My App</h1>
      //       </div>
      //     </div>
      //   {children}

      //   <footer className="text-center mt-4">
      //     <p>© 2023 My App. All rights reserved.</p>  
      //   </footer>
      //   </div>
        
      // </body> 

     
 
<body>

 
  <div className="header">
    <h1 className="mb-3">tierlich.</h1>
    <div className="container px-1">
      <div className="progress">
        <div className="progress-bar" role="progressbar"  ></div>
      </div>
    </div>
  </div>   
  <div className="content">
       {children}
  </div>  
  <div className="footer">
    <button>&larr; Zurück</button>
    <button>Weiter</button>
  </div>

</body>
 

      }
      
    </html>
  );
}
